os:
  - linux

language: python
dist: focal

python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11

addons:
  chrome: stable

install:
  - pip install --upgrade pip
  - pip install -e .
  - pip install tox-travis

script:
  - tox
