os:
  - linux

language: python
dist: focal

env:
  global:
    - CAMPFIRE_TOKEN=abc123

python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11

addons:
  chrome: stable

install:
  - python3 -m pip install --upgrade pip # Fix error on travis python 3.9 build
  - pip install -e .
  - pip install tox-travis

script:
  - tox
