os:
  - linux

language: python
dist: focal

python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11

before_script:
  - export MY_VAR=master

addons:
  chrome: stable

install:
  - python3 -m pip install --upgrade pip # Fix error on travis python 3.9 build
  - pip install -e .
  - pip install tox-travis

script:
  - tox
