language: python

os:
  - linux

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

dist: xenial

services:
  - xvfb

addons:
  chrome: stable

install:
  - pip install -e .
  - pip install tox-travis

script:
  - tox
