os:
  - linux

language: python
matrix:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11

dist: xenial

services:
  - xvfb

addons:
  chrome: stable

install:
  - pip install -e .
  - pip install tox-travis

script:
  - tox
