[project]
name = "google-images-downloader"
description = "Script to download images from a \"Google Images\" query"
version = "1.0.2"
authors = [
    { name = "Harkame" }
]
readme = "README.md"
classifiers = ["Programming Language :: Python"]

[project.urls]
repository = "https://github.com/Harkame/google-images-downloader"

[build-system]
requires = [
    "selenium",
    "requests",
    "pillow",
    "chromedriver-py",
    "fake_useragent",
    "tqdm",
    "setuptools>=65.0.0"
]

build-backend = "setuptools.build_meta"

[project.scripts]
google-images-downloader = "google_images_downloader.main:main"