name: Coverage
on:
  push:

concurrency:
  group: ${{ github.ref }}-coverage
  cancel-in-progress: true

jobs:
  test:
    environment: build
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.11"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - uses: browser-actions/setup-chrome@v1
      - if: ${{ matrix.os == 'macos-latest' }}
        run: chromium --version
      - if: ${{ matrix.os != 'macos-latest' }}
        run: chrome --version
      - uses: browser-actions/setup-firefox@v1
      - run: firefox --version
      - name: Install tests dependencies
        run: pip install pytest pytest-cov
      - name: Install package dependencies
        run: pip install -e .
      - name: Run test suite
        run: pytest --cov=google_images_downloader --cov-report xml:coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish code coverage to Code Climate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ./coverage.xml:coverage.py
      - name: Publish code coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.xml
      - name: Publish code coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: ./coverage.xml
          github-token: ${{ github.token }}